// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAo_fWlQCUqo8xWLh3Q_CI8Wm5ohC0kNOk',
    appId: '1:1078413552979:web:26bb9492e56b66f39d85a6',
    messagingSenderId: '1078413552979',
    projectId: 'bikepool-4c5f5',
    authDomain: 'bikepool-4c5f5.firebaseapp.com',
    storageBucket: 'bikepool-4c5f5.firebasestorage.app',
    measurementId: 'G-V7736NVNBK',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC-P2FcnRXmhcdee4hBSIEDcIJOHWMaCTc',
    appId: '1:1078413552979:android:36c585b227d5505e9d85a6',
    messagingSenderId: '1078413552979',
    projectId: 'bikepool-4c5f5',
    storageBucket: 'bikepool-4c5f5.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAo_fWlQCUqo8xWLh3Q_CI8Wm5ohC0kNOk',
    appId: '1:1078413552979:web:6d31c4f0b90dbf129d85a6',
    messagingSenderId: '1078413552979',
    projectId: 'bikepool-4c5f5',
    authDomain: 'bikepool-4c5f5.firebaseapp.com',
    storageBucket: 'bikepool-4c5f5.firebasestorage.app',
    measurementId: 'G-05XLTS7J42',
  );
}
